### PR TITLE
Fixed patch of Spring boot app starts at 8181 port and error log for api key and authtoken  

### PR DESCRIPTION
**Pull request by asaraogi**
### Desired Outcome

- Spring boot application is not running in 8181 port .
- User will only get error message , Please provide Conjur Authn Token file or else api Key when not providing both of them.

### Implemented Changes

*Describe how the desired outcome above has been achieved with this PR. In
particular, consider:*

- _What's changed? Why were these changes made?_
- _How should the reviewer approach this PR, especially if manual tests are required?_
- _Are there relevant screenshots you can add to the PR description?_

### Connected Issue/Story

Resolves # https://github.com/cyberark/conjur-spring-boot-sdk/issues/64

CyberArk internal issue link: https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-23326

### Definition of Done
*At least 1 todo must be completed in the sections below for the PR to be
merged.*

#### Changelog

- [ ] The CHANGELOG has been updated, or
- [x] This PR does not include user-facing changes and doesn't require a
  CHANGELOG update

#### Test coverage

- [x] This PR includes new unit and integration tests to go with the code
  changes, or
- [ ] The changes in this PR do not require tests

#### Documentation

- [ ] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]()
- [x] This PR does not require updating any documentation

#### Behavior

- [ ] This PR changes product behavior and has been reviewed by a PO, or
- [ ] These changes are part of a larger initiative that will be reviewed later, or
- [x] No behavior was changed with this PR

#### Security

- [ ] Security architect has reviewed the changes in this PR,
- [ ] These changes are part of a larger initiative with a separate security review, or
- [ ] There are no security aspects to these changes

### CODE REVIEW

**Review by itsbrugu — COMMENTED** [review]
where are junits?

Can you also include the Jenkins pipeline link for the branch to show successful builds.

**Comment by nitincyberark** [comment]
Here is the Jenkins links : https://jenkins.conjur.net/view/cyberark/job/cyberark--conjur-spring-boot-sdk/job/jira23323/

**Comment by asaraogi** [comment]
@itsbrugu  , additional junits are not required as we included all necessary previously only , it was failing because of additional and operator condition  which is fixed . Now it is working fine.

jenkins pipeline link - https://jenkins.conjur.net/view/cyberark/job/cyberark--conjur-spring-boot-sdk/job/errorLogAndDefaultPortFixed/

**Comment by asaraogi** [comment]
okhttps v3.14.9 is changed to v4.10.0  in both of the pom files.

**Review by itsbrugu — APPROVED** [review]

**Pull request merged**
